### ISSUE TITLE
修正创建型模式-单例模式-元类.py的一个输出值

### ISSUE THREAD

**Issue by zengzzzzz** [ydf0509/python36patterns#2]
![image](https://user-images.githubusercontent.com/49514822/174005980-ad8a897f-79e9-4c5e-80e0-3e0185754fcb.png)
这个位置，按照代码实现，a3应该是和a1是同一个对象，并无动态传参初始化，输出应该是  “ 001 吃饭 ”，您可以验证一下。谢谢。

**Comment by ydf0509** [comment]
对，享元模式是打印003吃饭，单利模式是打印001吃饭
